### ISSUE TITLE
asciidoctor attributes set in the config file do not affect asciidoctor (though they seem to be parsed correctly)

### ISSUE THREAD

**Issue by ghost** [PolymathArtisan/multi-mark-maker#6]
My config file looks like this:

```toml
in-format = "asciidoctor"

[asciidoctor-options]
  [asciidoctor-options.attribute]
  source-highlighter = "pygments"
  last-update-label = false
```

But the attributes set under `[asciidoctor-options.attribute]` don't seem to affect the html part of the mutlipart emails. (e.g. there is still a last updated label at the bottom).

If I add `print(' '.join(cmd))` on line 383, then I get the expected value: 

```shell
asciidoctor --attribute=source-highlighter=pygments --attribute=last-update-label! -o - -
```

If I then `cat` a tester email body into that command though, the output is as expected! (with no last-updated label). 

So it seems that the options just aren't being interpretted by asciidoctor. But clearly the conversion is at least _working_ because I do get an html output! And the styling of the html is consistent with asciidoctor's output, so it's come from asciidoctor. If I manually edit the asciidoctor cmd to be wrong, then asciidoctor gives me errors on stdout, but no such errors arise with the current code so the options are presumably being parsed and passed correctly.

I'm very confused.
